# Generated by Django 4.2.6 on 2023-10-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_user', '0002_alter_task_date_of_creation_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_creation',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
