version: '3.11'


services:
  db:
    image: nouchka/sqlite3:latest
    environment:
      - SQLITE3_DB=db.sqlite3
    expose:
      - 5432
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python3 /app/manage.py collectstatic --noinput --clear && gunicorn task_management.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db




#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    entrypoint: wsgi-entrypoint
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    environment:
#      - DJANGO_SECRETKEY_KEY='django-insecure-v572=1pcd3v%!tvpo4a!m1m!atk+@6%uehh%3ris%^1er42@g@'
#      - DJANGO_DEBUG = True
#    depends_on:
#      - db
#
#  db:
#    image: sqlite3

